### ISSUE TITLE
#ITEM 1 - Document proofs for save Curve criteria

### ISSUE THREAD

**Issue by Bounce23** [dusk-network/dusk-zerocaf#13]
This issue lives under the item: https://gitlab.dusk.network/dusk-org/tech/issues/1

Create a document to show that Doppio meets the safe curve criteria. 
Listed at https://safecurves.cr.yp.to/

**Comment by Bounce23** [comment]
This issue will stay open but a more malleable area of the repo will be used to fully document the checklist as the document is being made. This is to allow for continuous improvements.

**Comment by Bounce23** [comment]
Found [here](https://github.com/dusk-network/dusk-corretto/blob/master/docs/Safe%20Curve%20criteria)

**Comment by Bounce23** [comment]
For the final section of the safe curve criteria, a new elligator hashing 2 algorithm needs to be found. As the existing from safe curves doc will not compile in rust.

**Comment by CPerezz** [comment]
Why won't compile? We can adapt it to HTML as done with the rest of the docs.

We can also try to inject LaTeX on it. 

Math demonstrations are done btw?

**Comment by Bounce23** [comment]
- I'm not sure, its an existing algorithm. It's probably much like the others - in that it needs to be tweaked due to our field abstraction. 
- I don't think that injection is applicable here. 
- Yes, I have about 90% all of the documented maths and all saved `sage` code 
- Also, on the topic of curve criteria and that bearing in mind we have just created `edwards` demos. When checking legendre symbol, so therefore the proofs of quadratic residues in L, of the basepoint, it will not show as a square. Giving a `-1` output. This is for the point x  = 17. The reasoning is the symmetry doesn't permeate the basepoint. This is just a note. I will add it to the relevant notes and push it.

**Comment by CPerezz** [comment]
>     * I'm not sure, its an existing algorithm. It's probably much like the others - in that it needs to be tweaked due to our field abstraction.
> 
>     * I don't think that injection is applicable here.
> 
>     * Yes, I have about 90% all of the documented maths and all saved `sage` code
> 
>     * Also, on the topic of curve criteria and that bearing in mind we have just created `edwards` demos. When checking legendre symbol, so therefore the proofs of quadratic residues in L, of the basepoint, it will not show as a square. Giving a `-1` output. This is for the point x  = 17. The reasoning is the symmetry doesn't permeate the basepoint. This is just a note. I will add it to the relevant notes and push it.

I'll try to get a python version, which by far will be the most implemented and the easiest to work with Sage.
If I can help on something just ping me. Meanwhile I'll be with #50, #32 and #48.

**Comment by CPerezz** [comment]
Was this finnished on #71 and #72 merges? Can we close it?

**Comment by Bounce23** [comment]
Hashing to curve is now complete. The Elligator mapping wad realised during the building of the ristretto basepoint. 

As a result, this can be closed and I shall push all the code; as well as finish the paper to publish.

**Comment by CPerezz** [comment]
Perfect!!
Nice job!!!
