### ISSUE TITLE
#ITEM 2 - Get testing values for Point Operations.

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/dusk-zerocaf#31]
We need to get values to test the implementations done for:

- Point Addition.
- Point Subtraction.
- Point Doubling.
- Point Compression.
- TwEdws -> Montgomery Conversion.

We should get the values and the expected results with sage in order to be able to test every operation.

**Comment by Bounce23** [comment]
For the point operations, we ill use these computed values:

(4, 2*sqrt[1386409]) & (18, 2*sqrt[1386409]). Using indentity points for T & Z in extended co-oridnates, (X : Y : Z : T)

Point addition using addition formulae to derive point: 

`sage: x1 = 4 \\
sage: x2 = 18 \\
sage: y1 = 2*sqrt(1386409)\\
sage: y2 = 2*sqrt(1386409)\\
sage: x3 = (x1*y2)+(y1*x2)/1+d*x1*x2*y1*y2\\
sage: x3\\
44*sqrt(1386409) - 17298857295504/43325\\
sage: a = -1\\
sage: y3 = (y1*y2 - a*x1*x2)/1-d*x1*x2*y1*y2\\ 
sage: y3\\
17539125094604/43325`

To find point: (44*sqrt(1386409) - 17298857295504/43325, 17539125094604/43325)

**Comment by CPerezz** [comment]
After trying the values provided earlier, we are not passing the Point Addition test. So we need to check if we are obtaining the points correctly. Since the algorithm is pretty straightforward.

**Comment by CPerezz** [comment]
By using the Legendre Symbol and the Tonelli-Shanks algorithm. We've been able to get valid y coordinates for Twisted Edwards Points on Cartesian Coordinates.

Once there, the Points have been moved to the Twisted Edwards Extended Coordinates format, and we got:
```rust
pub static P1: EdwardsPoint = EdwardsPoint {
        X: FieldElement([23, 0, 0, 0, 0]),
        Y: FieldElement([1664892896009688, 132583819244870, 812547420185263, 637811013879057, 13284180325998]),
        Z: FieldElement([1, 0, 0, 0, 0]),
        T: FieldElement([4351986304670635, 4020128726404030, 674192131526433, 1158854437106827, 6468984742885])
    };

    pub static P2: EdwardsPoint = EdwardsPoint {
        X: FieldElement([68, 0, 0, 0, 0]),
        Y: FieldElement([1799957170131195, 4493955741554471, 4409493758224495, 3389415867291423, 16342693473584]),
        Z: FieldElement([1, 0, 0, 0, 0]),
        T: FieldElement([3505259403500377, 292342788271022, 2608000066641474, 796697979921534, 2995435405555])
    };
```

These points come from random x's that had a y existing over the field GF(P).
