### ISSUE TITLE
Implement 4-coset function for `RistrettoPoint`

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/dusk-zerocaf#80]
Be able to print the 4-coset where a `RistrettoPoint` lives could be really helpful in order to debug lots of conversions and functions inside of this library.

The 4cosets where `EdwardsPoints` are aggregated in order to encode their values to the Ristretto Scalar Field, are defined here: https://ristretto.group/details/isogeny_encoding.html#torquing-points-to-lift-mathcal-e--mathcal-e4-to-mathcal-e--mathcal-e2-
and also on the [Decaf paper Section 3.0](https://www.shiftleft.org/papers/decaf/decaf.pdf).

I recently took them values and checked them against the curve25519-dalek library (they had a cyclic 8-torsion group defined where 4 of the points where the way for going to the 4-coset points of the given `RistrettoPoint`). See [this section of their code](https://github.com/dalek-cryptography/curve25519-dalek/blob/cf03d39f0fc3e1c625b9f1e9be0473758b324526/src/backend/serial/u64/constants.rs#L63).

The points obtained where:
```
// Ristretto EIGH TORSION curve25519-dalek
// (X, Y, Z, T) in descendent order format.
0
1
1
0


14399317868200118260347934320527232580618823971194345261214217575416788799818
55188659117513257062467267217118295137698188065244968500265048394206261417927
1
49249569669750663008941572433996126643240416652669157144375776867115012622209


38214883241950591754978413199355411911188925816896391856984770930832735035197 -sqrt(a) // 1/sqrt(a)
0
1
0


14399317868200118260347934320527232580618823971194345261214217575416788799818
2707385501144840649318225287225658788936804267575313519463743609750303402022
1
8646474948907434702843920070347827283394575680151124875353015136841552197740


0
57896044618658097711785492504343953926634992332820282019728792003956564819948  a
1
0


43496726750457979451437558183816721346016168361625936758514574428539776020131
2707385501144840649318225287225658788936804267575313519463743609750303402022
1
49249569669750663008941572433996126643240416652669157144375776867115012622209


19681161376707505956807079304988542015446066515923890162744021073123829784752 (sqrt(a))
0
1
0


43496726750457979451437558183816721346016168361625936758514574428539776020131
55188659117513257062467267217118295137698188065244968500265048394206261417927
1
8646474948907434702843920070347827283394575680151124875353015136841552197740
```

The ones we are interested in (which are already the easiest) are:
```
- The RistrettoPoint that we used as input (Which = P).

- `P + (-sqrt(a), 0, 1, 0)`.

- `P + (0, a, 1, 0)`.

- `P + (sqrt(a), 0, 1, 0)`.
```

**Comment by Bounce23** [comment]
This issue will work inline with the most recent comment on #78. Perhaps it will be best to use this as a solution as it is an amalgamation for the pair of them. 

---
To explain how the coset is found and formed, it first needs to be understood how the coset, `E[4]` is found and how it is taken, via the difference in torquing points, from `E[2]`. This will be done on paper and then I will upload the image(s) to this issue.
