### ISSUE TITLE
#ITEM 2 - Document update for new curve constants.

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/dusk-zerocaf#82]
Since we derived a new curve from a modified version of this @ebfull script:
https://github.com/zkcrypto/jubjub/blob/master/doc/derive/derive.sage

We got new constants and then the Curve order & the Sub-group order changed.

The scalar backend was refactored & documented again with the proper values, and constants modules too. See: 405f5417 & e1a92497

But we need to:
- Refactor Readme and library comments with the new curve name and constant values.
- Refactor the doc-comments.
- Refactor the Sage scripts that need it.

**Comment by CPerezz** [comment]
This closes #76 for my side.

**Comment by Bounce23** [comment]
The read me and pdf documents have been updated. They will require only a pushing later today. Then all the new parameters will be visible, thus I am closing this issue.
