### ISSUE TITLE
ITEM #2 - Review and improve current docs and add the Ristretto ones.

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/dusk-zerocaf#88]
Lots of functions can have examples on the docs.

Also the current examples and doc-comments should be reviewed according to the new curve that we are using and probably we should update some function comments in respect of that.

**Comment by Bounce23** [comment]
I have begun this process and will have it completed today. The majority are in the open pull request and then there are only a few extra which require our joint attention, which I have noted privately.

**Comment by Bounce23** [comment]
I have completed this process. In my last pull request I merged all the listed tasks so the issue can be closed.
