### ISSUE TITLE
Implement `serde` for the structures (Scalar, CompressedRistretto, etc)

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/dusk-zerocaf#95]

**Comment by CPerezz** [comment]
Are you planning to do it? Or you want me to go for it? It is something I should have done before..

**Comment by vlopes11** [comment]
Not needing this now, just opened for the future when we have some available effort to plan it (me, you or someone else)

**Comment by CPerezz** [comment]
I'd like to take it if it's ok for you. Long time since I don't implement serde. Will probably do it during my vacations (if it's not needed now or in a rush..)
