### ISSUE TITLE
Knowledge of a secret key

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/dusk-zerocaf#96]
Create a code snippet that works as follows:

Given a `Scalar` `a` that, provided only `a · G`, you prove you know `a` without revealing `a`.

Preferably with bulletproofs

**Comment by CPerezz** [comment]
https://github.com/zcash/zcash/issues/4254
https://github.com/zcash/zcash/issues/3924
https://github.com/ebfull/halo/blob/master/src/gadgets/ecc.rs

Worth to check

**Comment by CPerezz** [comment]
For some reasin the issue was closed.
It won't be until https://github.com/dusk-network/bulletproofs_gadgets/issues/5 is closed.

**Comment by CPerezz** [comment]
This issue can be considered as closed atm. 
There are some issues we need to fix but for our use case and as it is non-production ready, we can relay on it until we finish the impl.
